<?php
/**
 * Costs Management Page
 * Manages Costs with hierarchical location selection and period-based pricing
 * Hierarchy: Country -> Region -> City -> Cost -> Period -> Item -> Prices
 */

session_start();

// Define base path
$basePath = '../../';

// Check if user is logged in
if (!isset($_SESSION['user_id'])) {
    header('Location: ' . $basePath . 'login.php');
    exit;
}

// Load translation helper
require_once $basePath . 'includes/translations.php';

// Load security helpers for CSRF token
require_once $basePath . 'includes/security.php';

// Get translations
$t_sidebar = $all_translations['sidebar'] ?? [];
$t_common = $all_translations['common'] ?? [];
$t_costs = $all_translations['costs'] ?? [];
?>
<!DOCTYPE html>
<html lang="<?php echo $lang; ?>">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=5.0, user-scalable=yes, viewport-fit=cover">
    <title><?php echo $t_costs['costs'] ?? 'Costs'; ?> - <?php echo $all_translations['app']['name'] ?? 'FST Cost Management'; ?></title>
    
    <!-- Google Fonts for Icons -->
    <link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Material+Symbols+Rounded:opsz,wght,FILL,GRAD@24,400,0,0" />
    
    <!-- CSS Files -->
    <link rel="stylesheet" href="<?php echo $basePath; ?>assets/css/includes/sidebar.css">
    <link rel="stylesheet" href="<?php echo $basePath; ?>assets/css/includes/topbar.css">
    <link rel="stylesheet" href="<?php echo $basePath; ?>assets/css/common.css">
    <link rel="stylesheet" href="<?php echo $basePath; ?>assets/css/confirm-dialog.css">
    <link rel="stylesheet" href="<?php echo $basePath; ?>assets/css/select-search.css">
    <link rel="stylesheet" href="<?php echo $basePath; ?>assets/css/app/definitions/costs.css">
    
    <link rel="icon" type="image/svg+xml" href="<?php echo $basePath; ?>assets/images/logo.svg">
</head>
<body>
    <?php include $basePath . 'includes/sidebar.php'; ?>
    
    <div class="main-content">
        <?php include $basePath . 'includes/topbar.php'; ?>
        
        <!-- Main Content Area -->
        <div class="content-wrapper">
            <div class="costs-container">
                <!-- Page Header -->
                <div class="costs-header">
                    <h1 id="costsPageTitle"><?php echo $t_costs['costs'] ?? 'Costs'; ?></h1>
                </div>
                
                <!-- Tab Content -->
                <div class="costs-content" id="costs-content">
                    <!-- Content will be loaded by JavaScript -->
                </div>
            </div>
        </div>
    </div>
    
    <!-- Cost Modal -->
    <div class="modal" id="costsModal" tabindex="-1" role="dialog" aria-labelledby="costModalTitle" aria-modal="true">
        <div class="modal-content modal-content-large">
            <div class="modal-header">
                <div class="modal-title-wrapper">
                    <span class="material-symbols-rounded modal-icon">payments</span>
                    <h2 id="costModalTitle"><?php echo $t_costs['add_cost'] ?? 'Add Cost'; ?></h2>
                </div>
                <button class="btn-close" aria-label="<?php echo $t_common['close'] ?? 'Close'; ?>" title="<?php echo $t_common['close'] ?? 'Close'; ?>">
                    <span class="material-symbols-rounded">close</span>
                </button>
            </div>
            <form id="costForm" novalidate>
                <div class="modal-body">
                    <!-- Cost Code and Cost Name - Side by Side -->
                    <div class="form-row">
                        <!-- Cost Code (Read-only) -->
                        <div class="form-group">
                            <label>
                                <?php echo $t_costs['cost_code'] ?? 'Cost Code'; ?>
                                <span class="info-icon" title="<?php echo $t_costs['cost_code_info'] ?? 'Cost code is automatically generated by the system'; ?>">
                                    <span class="material-symbols-rounded info-icon-small">info</span>
                                </span>
                            </label>
                            <input type="text" name="cost_code" id="costCodeInput" readonly placeholder="<?php echo $t_costs['cost_code_auto'] ?? 'Auto-generated (FST...)'; ?>" class="input-readonly">
                            <small class="form-hint">
                                <span class="material-symbols-rounded">info</span>
                                <?php echo $t_costs['cost_code_info'] ?? 'Cost code is automatically generated by the system'; ?>
                            </small>
                        </div>
                        
                        <!-- Cost Name -->
                        <div class="form-group">
                            <label><?php echo $t_costs['cost_name'] ?? 'Cost Name'; ?> *</label>
                            <input type="text" name="name" placeholder="<?php echo $t_costs['cost_name'] ?? 'Cost Name'; ?>" required data-error="<?php echo ($t_costs['cost_name'] ?? 'Cost Name') . ' ' . ($t_common['is_required'] ?? 'is required'); ?>">
                            <span class="input-error-message"></span>
                        </div>
                    </div>
                    
                    <!-- Location Selection - Side by Side -->
                    <div class="form-row">
                        <div class="form-group">
                            <label><?php echo $t_sidebar['country'] ?? 'Country'; ?> *</label>
                            <select name="country_id" id="countrySelect" required data-error="<?php echo ($t_sidebar['country'] ?? 'Country') . ' ' . ($t_common['is_required'] ?? 'is required'); ?>">
                                <option value=""><?php echo $t_costs['select_country'] ?? 'Select Country'; ?></option>
                            </select>
                            <span class="input-error-message"></span>
                        </div>
                        
                        <div class="form-group">
                            <label><?php echo $t_sidebar['region'] ?? 'Region'; ?> *</label>
                            <select name="region_id" id="regionSelect" required disabled data-error="<?php echo ($t_sidebar['region'] ?? 'Region') . ' ' . ($t_common['is_required'] ?? 'is required'); ?>">
                                <option value=""><?php echo $t_costs['select_region'] ?? 'Select Region'; ?></option>
                            </select>
                            <span class="input-error-message"></span>
                        </div>
                        
                        <div class="form-group">
                            <label><?php echo $t_sidebar['city'] ?? 'City'; ?> *</label>
                            <select name="city_id" id="citySelect" required disabled data-error="<?php echo ($t_sidebar['city'] ?? 'City') . ' ' . ($t_common['is_required'] ?? 'is required'); ?>">
                                <option value=""><?php echo $t_costs['select_city'] ?? 'Select City'; ?></option>
                            </select>
                            <span class="input-error-message"></span>
                        </div>
                    </div>
                    
                    <!-- Periods Section -->
                    <div class="form-group">
                        <div class="form-group-header">
                            <label><?php echo $t_costs['periods'] ?? 'Periods'; ?></label>
                            <button type="button" class="btn-secondary btn-sm" id="addPeriodBtn">
                                <span class="material-symbols-rounded">add</span>
                                <?php echo $t_costs['add_period'] ?? 'Add Period'; ?>
                            </button>
                        </div>
                        <div id="periodsContainer" data-empty-message="<?php echo $t_costs['no_periods_added'] ?? 'No periods added yet. Click "Add Period" to add one.'; ?>">
                            <!-- Periods will be added here dynamically -->
                        </div>
                    </div>
                </div>
                
                <div class="modal-footer">
                    <button type="button" class="btn-secondary" id="cancelCostBtn">
                        <span class="material-symbols-rounded">close</span>
                        <?php echo $t_common['cancel'] ?? 'Cancel'; ?>
                    </button>
                    <button type="submit" class="btn-primary" id="saveCostBtn">
                        <span class="material-symbols-rounded">save</span>
                        <?php echo $t_common['save'] ?? 'Save'; ?>
                        <span class="btn-loading-spinner">
                            <span class="material-symbols-rounded loading-spinner">sync</span>
                        </span>
                    </button>
                </div>
            </form>
        </div>
    </div>
    
    <!-- Page configuration for JavaScript -->
    <script type="application/json" id="page-config">
    <?php
    echo json_encode([
        'basePath' => $basePath,
        'apiBase' => $basePath . 'api/definitions/costs.php',
        'csrfToken' => csrfToken(),
        'translations' => [
            'costs' => $t_costs,
            'common' => $t_common,
            'sidebar' => $t_sidebar
        ]
    ], JSON_HEX_TAG | JSON_HEX_AMP | JSON_HEX_APOS | JSON_HEX_QUOT | JSON_PRETTY_PRINT);
    ?>
    </script>
    
    <!-- Toast Notification Container -->
    <div id="toastContainer" class="toast-container"></div>
    
    <link rel="stylesheet" href="<?php echo $basePath; ?>assets/css/date-range-picker.css">
    <script src="<?php echo $basePath; ?>assets/js/includes/sidebar.js"></script>
    <script src="<?php echo $basePath; ?>assets/js/toast.js"></script>
    <script src="<?php echo $basePath; ?>assets/js/common.js"></script>
    <script src="<?php echo $basePath; ?>assets/js/select-search.js"></script>
    <script src="<?php echo $basePath; ?>assets/js/date-range-picker.js"></script>
    <script src="<?php echo $basePath; ?>assets/js/app/definitions/costs.js"></script>
</body>
</html>

